环境测试完成合并CI

diff --git a/.github/workflows/yaming.yml b/.github/workflows/yaming.yml
--- a/.github/workflows/yaming.yml
+++ b/.github/workflows/yaming.yml
@@ -59,3 +59,40 @@ jobs:
           file: Binaries/*.zip
           tag: ${{ github.ref }}
           file_glob: true
+  build-linux:
+    name: linux-clang构建
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: 安装依赖环境
+        run: |
+          sudo apt-get update
+          sudo apt-get install nasm uuid-dev libssl-dev iasl
+          file="clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04"
+          suf=".tar.xz"
+          curl -LO "https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/${file}${suf}" || exit 1
+          sum=$(shasum -a 256 "${file}${suf}" | cut -f1 -d' ')
+          expsum="2c2fb857af97f41a5032e9ecadf7f78d3eff389a5cd3c9ec620d24f134ceb3c8"
+          if [ "$sum" != "$expsum" ]; then echo "Invalid checksum $sum" ; exit 1 ; fi
+          tar -xf "${file}${suf}" || exit 1
+          echo "$(pwd)/${file}/bin" >> $GITHUB_PATH
+      - name: CI Bootstrap
+        run: |
+          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/ocbuild/Yaming/ci-bootstrap.sh) && eval "$src" || exit 1
+      - run: ./build_duet.tool
+      - run: ./build_oc.tool
+
+      - name: Upload to Artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: OpenCore_Linux_build
+          path: Binaries/*.zip
+      - name: 上传发布版本
+        if: github.event_name == 'release'
+        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
+        with:
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: Binaries/*.zip
+          tag: ${{ github.ref }}
+          file_glob: true
